import { NextPage } from 'next';
import Head from 'next/head'
import LayoutHomePageProps from '../../interfaces/layouts/home'
import Image from 'next/image';
import { useRouter } from 'next/router';

const LayoutHomePage: NextPage<LayoutHomePageProps> = ({ children, ...props }: LayoutHomePageProps) => {
  const router = useRouter();
  const currentPath = router.pathname;
  return (
    <>
    <Head>
        <title>{props.title}</title>
        <meta name={props.descripcion} content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <nav className="site-nav">
      <ul className="site-nav__list">
        <li>
          <Image
            src={currentPath == "/" ?"/images/icono.png":"/images/icono-pagina-removebg-preview.png"}
            alt="Banner"
            width={140}
            height={120}
            className={currentPath == "/" ?" ":"mt-2"}
          />
        </li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">NOSOTROS</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">PROPIEDADES</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">SERVICIOS</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">PROYECTOS</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">INVERSIONES</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link">CONTACTO</a></li>
      </ul>
    </nav>
    <main>
      
      {children}
    </main>
    </>
  );
};

export default LayoutHomePage;