import { ReactNode } from 'react';
import { NextPage } from 'next';
import Head from 'next/head'
import LayoutHomePageProps from '../../interfaces/layouts/home'

const LayoutHomePage: NextPage<LayoutHomePageProps> = ({ children, ...props }: LayoutHomePageProps) => {
  return (
    <>
    <Head>
        <title>{props.title}</title>
        <meta name={props.descripcion} content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      {children}
    </main>
    </>
  );
};

export default LayoutHomePage;