import { ReactNode } from 'react';
import { NextPage } from 'next';
import Head from 'next/head'
import LayoutHomePageProps from '../../interfaces/layouts/home'
import Image from 'next/image';
import Footer from '../components/footer';

const LayoutAllPage: NextPage<LayoutHomePageProps> = ({ children, ...props }: LayoutHomePageProps) => {
  return (
    <>
    <Head>
        <title>{props.title}</title>
        <meta name={props.descripcion} content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <nav className="site-nav-secondary">
      <ul className="site-nav__list">
        <li>
          <Image
            src="/images/icono-pagina-removebg-preview.png"
            alt="Banner"
            width={140}
            height={120}
            
          />
        </li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">HOME</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">SERVICE</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">NOSOTROS</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">PROYECTOS</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">INVERSIONES</a></li>
        <li className="site-nav__item"><a href="#" className="site-nav__link--secondary">CONTACTO</a></li>
      </ul>
    </nav>
    <main>
      {children}
    </main>
    <Footer></Footer>
    </>
  );
};

export default LayoutAllPage;